# Generated by Django 3.1 on 2022-04-20 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellerapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50, unique=True)),
                ('company_address', models.CharField(max_length=50)),
                ('company_state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], max_length=50)),
                ('company_city', models.CharField(max_length=50)),
                ('company_pincode', models.IntegerField()),
                ('company_gst_number', models.CharField(max_length=50)),
                ('company_registration_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_quantity', models.IntegerField()),
                ('product_barcode', models.CharField(max_length=12, unique=True)),
                ('product_description', models.CharField(max_length=50)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_stars', models.IntegerField(null=True)),
                ('review_comments', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review_Images',
            fields=[
                ('review_images_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_review_images', models.FileField(null=True, upload_to='media/product_review_images')),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.review')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questions_id', models.IntegerField(primary_key=True, serialize=False)),
                ('questions', models.CharField(max_length=100)),
                ('answers', models.CharField(max_length=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Images',
            fields=[
                ('product_images_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_image', models.FileField(upload_to='product_images')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Features',
            fields=[
                ('product_features_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_features_name', models.CharField(max_length=50)),
                ('product_features_value', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('product_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_category_name', models.CharField(max_length=50)),
                ('product_parent_category', models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home Appliances', 'Home Appliances'), ('Sports', 'Sports'), ('Groceries', 'Groceries')], max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Catalog',
            fields=[
                ('product_catalog_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_catalog_stock', models.IntegerField()),
                ('product_catalog_price', models.FloatField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.product')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller')),
            ],
        ),
    ]
